# Define the goal (parameter)
uint32 id
string control_task
---
# Define the result (return)
bool success
string control_task
string message
uint32 id
---
# Define a feedback message (progress)
string progress
